administrator/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'administrator'

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.login, name='login'),
    path('form_notice/', views.form_notice, name='form_notice'),
    path('form_dues_stu/', views.form_dues_stu, name='form_dues_stu'),
    path('form_dues_tea/', views.form_dues_tea, name='form_dues_tea'),
    path('form_hos/', views.form_hos, name='form_hos'),
    path('form_stu/', views.form_stu, name='form_stu'),
    path('form_tea/', views.form_tea, name='form_tea'),
]

darularkam/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', include('administrator.urls')),
    path('home/', include('home.urls')),
    path('hostel/', include('hostel.urls')),
    path('teacher/', include('teacher.urls')),
    path('school/', include('school.urls')),
    path('hifz/', include('hifz.urls')),
    path('notice/', include('notice.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

hifz/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'hifz'

urlpatterns = [
    path('', views.index, name='home'),
]

home/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='home'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
]

hostel/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'hostel'

urlpatterns = [
    path('', views.index, name='home'),
]

notice/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'notice'

urlpatterns = [
    path('', views.index, name='home'),
    path('details/', views.notice_details, name='details'),
]

school/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'school'

urlpatterns = [
    path('', views.index, name='home'),
]

teacher/urls.py
from django.urls import path, include
from django.views.decorators.cache import never_cache
from . import views

app_name = 'teacher'

urlpatterns = [
    path('', views.index, name='home'),
]

administrator/models.py
from django.db import models

# Create your models here.

hifz/models.py
from django.db import models

# Create your models here.

home/models.py
from django.db import models

# Create your models here.

hostel/models.py
from django.db import models

# Create your models here.

notice/models.py
from django.db import models

# Create your models here.

school/models.py
from django.db import models

# Create your models here.

teacher/models.py
from django.db import models

# Create your models here.

administrator/forms.py
from django import forms


class NoticeForm(forms.Form):
    title = forms.CharField(
        max_length=200,
        label='Write title',
        widget=forms.TextInput(),
    )
    details = forms.CharField(
        max_length=2000,
        label='Write details',
        widget=forms.Textarea(
            attrs={
                'rows': '40',
            }
        ),
    )

    def clean(self):
        cleaned_data = super(NoticeForm, self).clean()
        title = cleaned_data.get('title')
        details = cleaned_data.get('details')
        if not title and not details:
            raise forms.ValidationError('You have to write something!')

administrator/views.py
from django.shortcuts import render
from .forms import NoticeForm


# Create your views here.
def index(request):
    return render(request, 'administrator/pages/index.html')


def login(request):
    return render(request, 'administrator/pages/login.html')


def form_notice(request):
    if request.method == "POST":
        form = NoticeForm(request.POST)
        if form.is_valid():
            pass
    else:
        form = NoticeForm()
    return render(request, 'administrator/pages/form_notice.html', {'form': form})


def form_dues_stu(request):
    return render(request, 'administrator/pages/form_dues_stu.html')


def form_dues_tea(request):
    return render(request, 'administrator/pages/form_dues_tea.html')


def form_hos(request):
    return render(request, 'administrator/pages/form_hos.html')


def form_stu(request):
    return render(request, 'administrator/pages/form_stu.html')


def form_tea(request):
    return render(request, 'administrator/pages/form_tea.html')

hifz/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'hifz/pages/index.html')

home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'home/pages/index.html')


def about(request):
    return render(request, 'home/pages/about.html')


def contact(request):
    return render(request, 'home/pages/contact.html')

hostel/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'hostel/pages/index.html')

notice/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'notice/pages/index.html')


def notice_details(request):
    return render(request, 'notice/pages/notice_details.html')

school/views.py
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'school/pages/index.html')

teacher/views.py
from django.http import HttpResponse
from django.shortcuts import render


# Create your views here.
def index(request):
    return render(request, 'teacher/pages/index.html')

administrator/templates/administrator/pages/base.html
{% load static %}

{% block header %}

<!DOCTYPE html>
<html lang="en">

<head>

  <title>DARUL ARKAM SCHOOL & MADRASAH</title>
  <link rel="icon" href="{% static 'home/images/icon.png' %}" type="image/png" sizes="16x16">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'home/fonts/icomoon/style.css' %}">

  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/owl.theme.default.min.css' %}">

  <link rel="stylesheet" href="{% static 'home/css/jquery.fancybox.min.css' %}">

  <link rel="stylesheet" href="{% static 'home/css/bootstrap-datepicker.css' %}">

  <link rel="stylesheet" href="{% static 'home/fonts/flaticon/font/flaticon.css' %}">

  <link rel="stylesheet" href="{% static 'home/css/aos.css' %}">
  <link href="{% static 'home/css/jquery.mb.YTPlayer.min.css' %}" media="all" rel="stylesheet" type="text/css">

  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

  <link rel="stylesheet" href="{% static 'home/css/Contact-Form-Clean.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/sideber.css' %}">


</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>

    <header id="header" class="site-navbar js-sticky-header site-navbar-target" role="banner">
      <div class="">
        <div class="d-flex align-items-center">
          <div class="site-logo">
            <a href="{% url 'home:home' %}" class="d-block">
              <img id="logo" src="{% static 'home/images/logo1.png' %}" alt="Image" class="img-fluid ml-2" style="max-height: 40px;">
            </a>
          </div>
          <div class="ml-auto">
            <nav class="site-navigation position-relative text-right ex1" role="navigation">
              <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                <li class="active">
                  <a href="{% url 'administrator:home' %}" class="nav-link text-left">অ্যাডমিন</a>
                </li>
                <li>
                  <a href="{% url 'administrator:form_notice' %}" class="nav-link text-left">নোটিশ</a>
                </li>
                <li>
                  <a href="{% url 'administrator:form_dues_stu' %}" class="nav-link text-left">ছাত্র ফি</a>
                </li>
                <li>
                  <a href="{% url 'administrator:form_dues_tea' %}" class="nav-link text-left">শিক্ষক বেতন</a>
                </li>
                <li>
                  <a href="{% url 'administrator:form_hos' %}" class="nav-link text-left">হোস্টেল</a>
                </li>
                <li class="has-children">
                  <a href="#" class="nav-link text-left">নতুন যোগ</a>
                  <ul class="dropdown">
                    <li><a href="{% url 'administrator:form_stu' %}">Add Student</a></li>
                    <li><a href="{% url 'administrator:form_tea' %}">Add Teacher</a></li>
                  </ul>
                </li>
                <li>
                  <a href="{% url 'home:home' %}" class="nav-link text-left">ওয়েবপৃষ্ঠা যান</a>
                </li>
              </ul>
            </nav>
          </div>
          <div class="">
            <div class="social-wrap container vertical-center">
              <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black"><span
                class="icon-menu h3"></span></a>
            </div>
          </div>
        </div>
      </div>
    </header>

<div style="height: 100px;"></div>
<script>
document.getElementById("header").style.padding = "30px 10px";
var hl = document.getElementById('logo').offsetHeight;
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 80 || document.documentElement.scrollTop > 80) {
    document.getElementById("header").style.padding = "10px 10px";
    document.getElementById("logo").style.height = hl-hl*.1+"px";
    document.getElementById("logo").style.transition = ".35s ease-in-out";
  } else {
    document.getElementById("header").style.padding = "30px 10px";
    document.getElementById("logo").style.height = hl+"px";
    document.getElementById("logo").style.transition = ".35s ease-in-out";
  }
}
</script>

{% endblock %}

{% block coversection %}

{% endblock %}

{% block content %}

{% endblock %}

{% block footer %}

  <!-- loader -->
      <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"></circle><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#51be78"></circle></svg></div>

  </div>

</body>

</html>

        <script src="{% static 'home/js/jquery-3.3.1.min.js' %}"></script>
      <script src="{% static 'home/js/jquery-migrate-3.0.1.min.js' %}"></script>
      <script src="{% static 'home/js/jquery-ui.js' %}"></script>
      <script src="{% static 'home/js/popper.min.js' %}"></script>
      <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
      <script src="{% static 'home/js/owl.carousel.min.js' %}"></script>
      <script src="{% static 'home/js/jquery.stellar.min.js' %}"></script>
      <script src="{% static 'home/js/jquery.countdown.min.js' %}"></script>
      <script src="{% static 'home/js/bootstrap-datepicker.min.js' %}"></script>
      <script src="{% static 'home/js/jquery.easing.1.3.js' %}"></script>
      <script src="{% static 'home/js/aos.js' %}"></script>
      <script src="{% static 'home/js/jquery.fancybox.min.js' %}"></script>
      <script src="{% static 'home/js/jquery.sticky.js' %}"></script>
      <script src="{% static 'home/js/jquery.mb.YTPlayer.min.js' %}"></script>
      <script src="{% static 'home/js/main.js' %}"></script>

{% endblock %}

administrator/templates/administrator/pages/form_dues_stu.html
{% extends 'administrator/pages/base.html' %}

{% load static %}

{% block content %}

    <div class="contact-clean mx-5 my-5">
        <div class="container">
            <p>All pages data:</p>
        </div>
    </div>

{% endblock %}

administrator/templates/administrator/pages/form_dues_tea.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

administrator/templates/administrator/pages/form_hos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

administrator/templates/administrator/pages/form_notice.html
{% extends 'administrator/pages/base.html' %}

{% load static %}

{% load widget_tweaks %}

{% block coversection %}

    <div class="site-section ftco-subscribe-1 site-blocks-cover pb-4" style="background-image: url('{% static 'home/images/bg_1.jpg' %}')">
        <div class="container">
          <div class="row align-items-end justify-content-center text-center">
            <div class="col-lg-7">
              <h2 class="mb-0">Notice</h2>
              <p>Lorem ipsum dolor sit amet consectetur adipisicing.</p>
            </div>
          </div>
        </div>
      </div>

{% endblock %}

{% block content %}

    <div class="contact-clean">
        <form action="{% url 'administrator:form_notice' %}" method="post" novalidate>
            {% csrf_token %}
            <h2>Write Notice</h2>

            {% for hidden_field in form.hidden_fields %}
                {{ hidden_field }}
            {% endfor %}

              {% if form.non_field_errors %}
                <div class="alert alert-danger" role="alert">
                  {% for error in form.non_field_errors %}
                    {{ error }}
                  {% endfor %}
                </div>
              {% endif %}

          {% for field in form.visible_fields %}
            <div class="form-group">
              {{ field.label }}

                  {% if form.is_bound %}
                    {% if field.errors %}
                      {% render_field field class="form-control is-invalid" %}
                      {% for error in field.errors %}
                        <div class="invalid-feedback">
                          {{ error }}
                        </div>
                      {% endfor %}
                    {% else %}
                      {% render_field field class="form-control is-valid" %}
                    {% endif %}
                  {% else %}
                    {% render_field field class="form-control" %}
                  {% endif %}

                  {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                  {% endif %}
                </div>
              {% endfor %}
                    <div class="form-group"><button class="btn btn-primary" type="submit">Submit</button></div>
                </form>
            </div>

{% endblock %}

administrator/templates/administrator/pages/form_stu.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

administrator/templates/administrator/pages/form_tea.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

home/templates/home/pages/base.html
{% load static %}

{% block header %}

<!DOCTYPE html>

<head>

  <title>DARUL ARKAM SCHOOL & MADRASAH</title>
  <link rel="icon" href="{% static 'home/images/icon.png' %}" type="image/png" sizes="16x16">
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <link href="{% static 'home/css/jquery.mb.YTPlayer.min.css' %}" media="all" rel="stylesheet" type="text/css">
  <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'home/fonts/icomoon/style.css' %}">
  <link rel="stylesheet" href="{% static 'home/fonts/flaticon/font/flaticon.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/font-awesome.min.css' %}">

  <link rel="stylesheet" href="{% static 'home/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/bootstrap-datepicker.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/jquery.fancybox.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/owl.theme.default.min.css' %}">

  <link rel="stylesheet" href="{% static 'home/css/aos.css' %}">
  <link rel="stylesheet" href="{% static 'home/css/style.css' %}">

</head>

<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>

    <header id="header" class="site-navbar js-sticky-header site-navbar-target" role="banner">
      <div class="">
        <div class="d-flex align-items-center">
          <div class="site-logo">
            <a href="{% url 'home:home' %}" class="d-block">
              <img id="logo" src="{% static 'home/images/logo1.png' %}" alt="Image" class="img-fluid ml-2" style="max-height: 40px;">
              <!-- <span style="float: none;">দারুল আরকাম স্কুল এন্ড মাদ্রাসা</span> -->
              <!-- <h6>asas</h6> -->
            </a>
          </div>
          <div class="ml-auto">
            <nav class="site-navigation position-relative text-right ex1" role="navigation">
              <ul class="site-menu main-menu js-clone-nav mr-auto d-none d-lg-block">
                <li class="active">
                  <a href="{% url 'home:home' %}" class="nav-link text-left">হোম</a>
                </li>
                <li class="has-children">
                  <a href="#" class="nav-link text-left">একাডেমিক তথ্য</a>
                  <ul class="dropdown">
                    <li><a href="{% url 'school:home' %}">স্কুল বিভাগ</a></li>
                    <li><a href="{% url 'hifz:home' %}">হিফ্জ বিভাগ</a></li>
                  </ul>
                </li>
                <li>
                  <a href="{% url 'hostel:home' %}" class="nav-link text-left">হোস্টেল</a>
                </li>
                <li>
                  <a href="{% url 'home:about' %}" class="nav-link text-left">আমাদের সম্পর্কে</a>
                </li>
                <li>
                    <a href="{% url 'home:contact' %}" class="nav-link text-left">যোগাযোগ</a>
                </li>
                <li>
                    <a href="{% url 'administrator:login' %}" class="nav-link text-left">লগইন</a>
                </li>
              </ul>
            </nav>
          </div>
          <div class="">
            <div class="social-wrap container vertical-center">
              <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black"><span
                class="icon-menu h3"></span></a>
            </div>
          </div>
        </div>
      </div>
    </header>

<div style="height: 70px;"></div>
<script>
document.getElementById("header").style.padding = "30px 10px";
var hl = document.getElementById('logo').offsetHeight;
window.onscroll = function() {scrollFunction()};

function scrollFunction() {
  if (document.body.scrollTop > 80 || document.documentElement.scrollTop > 80) {
    document.getElementById("header").style.padding = "10px 10px";
    document.getElementById("logo").style.height = hl-hl*.1+"px";
    document.getElementById("logo").style.transition = ".35s ease-in-out";
  } else {
    document.getElementById("header").style.padding = "30px 10px";
    document.getElementById("logo").style.height = hl+"px";
    document.getElementById("logo").style.transition = ".35s ease-in-out";
  }
}
</script>










<!--     <div class="py-2 bg-light">
      <div class="container">
          <div class="col-lg-9 d-none d-lg-block">
            <a href="#" class="small mr-3"><span class="icon-question-circle-o mr-2"></span> Have a questions?</a>
            <a href="#" class="small mr-3"><span class="icon-phone2 mr-2"></span> 10 20 123 456</a>
            <a href="#" class="small mr-3"><span class="icon-envelope-o mr-2"></span> info@mydomain.com</a>
          </div>
          <div class="col-lg-12 text-center">
            <a href="login.html" class="small mr-3"><span class="icon-unlock-alt"></span> Log In</a>
            <a href="register.html" class="small btn btn-primary px-4 py-2 rounded-0"><span class="icon-users"></span> Register</a>
          </div>
          <div class="col-lg-12 text-center">
            <h2 class="text-black">DARUL ARKAM SCHOOL & MADRASAH</h2>
            <h2 class="text-black">দারুল আরকাম স্কুল এন্ড মাদ্রাসা</h2>
          </div>
      </div>
    </div> -->



 <!--    Sadar Hospital Road, opposite the South Gate of Government Women's College, adjacent to the Old Driver Association, South Fourth, Comilla.  Phone: 081 - 74215 Mobile 01816859142, 01781 - 966030.
সদর হাসপাতাল রোড , সরকারি মহিলা কলেজের দক্ষিণ গেইটের বিপরীতে , পুরাতন ড্রাইভার সমিতি সংলগ্ন , দক্ষিণ চর্থা , কুমিল্লা । ফোনঃ 081 - 74215 মোবাইল 01816859142 , 01781 - 966030 ।

طريق مستشفى الصدر ، مقابل البوابة الجنوبية للكلية الحكومية للبنات ، بجوار جمعية السائقين القديمة ، الجنوب الرابع ، كوميلا.



হোম
আমাদের সম্পর্কে
একাডেমিক বিভাগ
কার্যক্রম
ইভেন্ট
নোটিশ
যোগাযোগ
-->









{% endblock %}



{% block content %}

{% endblock %}


{% block footer %}

    <div class="footer">
      <div class="container">
        <div class="row">
          <div class="col-lg-6">
            <!-- <p class="mb-4"><img src="images/logo1.png" alt="Image" class="img-fluid"></p> -->
            <!-- <h5>DARUL ARKAM SCHOOL & MADRASAH</h5> -->
            <h5>দারুল আরকাম স্কুল এন্ড মাদ্রাসা</h5>
            <p>মহান আল্লাহ ও তাঁর রাসূল সাল্লাল্লাহু আলাইহি ওয়াসাল্লামের সন্তুষ্টি অর্জনের লক্ষ্যে আহলে সুন্নাত ওয়াল জামাতের আকিদা অনুসারে আমলে-আখলাকে, লেবাসে-পোশাকে একদল আদর্শ ও দেশপ্রেমিক' আলেমেদ্বীন তৈরি করা।</p>
            <!-- <p><a href="#">আরও পড়ুন</a></p> -->
          </div>
          <div class="col-lg-3">
            <h3 class="footer-heading"><span>গুরুত্বপূর্ণ লিঙ্ক</span></h3>
            <ul class="list-unstyled">
                <li><a href="#">স্কুল বিভাগ</a></li>
                <li><a href="#">হিফ্জ বিভাগ</a></li>
                <li><a href="#">ভর্তি পরীক্ষা</a></li>
                <li><a href="#">বাংলাদেশ মাদ্রাসা শিক্ষা বোর্ড</a></li>
                <li><a href="#">মাধ্যমিক ও উচ্চমাধ্যমিক শিক্ষা বোর্ড, ঢাকা</a></li>
              <!--   <li><a href="#">মাদ্রাসা শিক্ষা অধিদপ্তর</a></li>
                <li><a href="#">শিক্ষা মন্ত্রণালয়</a></li> -->
            </ul>
          </div>
 <!--          <div class="col-lg-2">
              <h3 class="footer-heading"><span>Our Courses</span></h3>
              <ul class="list-unstyled">
                  <li><a href="#">Math</a></li>
                  <li><a href="#">Science &amp; Engineering</a></li>
                  <li><a href="#">Arts &amp; Humanities</a></li>
                  <li><a href="#">Economics &amp; Finance</a></li>
                  <li><a href="#">Business Administration</a></li>
                  <li><a href="#">Computer Science</a></li>
              </ul>
          </div> -->
          <div class="col-lg-3">
              <h3 class="footer-heading"><span>যোগাযোগ</span></h3>
              <ul class="list-unstyled">
                  <li><a href="#">সাহায্য কেন্দ্র</a></li>
                  <li><a href="#">সমর্থন কমিউনিটি</a></li>
                  <li><a href="#">আমাদেরকে বার্তা পাঠান </a></li>
                  <li><a href="#" class="medium"><span class="icon-phone2 mr-2"></span> 01521 304517</a> </li>
                  <li><a href="#" class="medium"><span class="icon-envelope-o mr-2"></span> info@mydomain.com</a> </li>
              </ul>
          </div>
        </div>

        <div class="row">
          <div class="col-12">
            <div class="copyright">
                <!-- <p>
                  Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | Developed by <a href="" target="_blank" >ATS-Core</a>
                </p> -->
                <p>
                   কপিরাইট © <script>document.write(new Date().getFullYear());</script><a href="" target="_blank" > ATS-Core </a> কর্তৃক সংরক্ষিত
                </p>
            </div>
          </div>
        </div>

      </div>
    </div>

  </div>
  <!-- .site-wrap -->


  <!-- loader -->
  <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px"><circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee"></circle><circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10" stroke="#51be78"></circle></svg></div>

  <script src="{% static  'home/js/jquery-3.3.1.min.js' %}"></script>
  <script src="{% static 'home/js/jquery-migrate-3.0.1.min.js' %}"></script>
  <script src="{% static 'home/js/jquery-ui.js' %}"></script>
  <script src="{% static 'home/js/popper.min.js' %}"></script>
  <script src="{% static 'home/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'home/js/owl.carousel.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.stellar.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.countdown.min.js' %}"></script>
  <script src="{% static 'home/js/bootstrap-datepicker.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.easing.1.3.js' %}"></script>
  <script src="{% static 'home/js/aos.js' %}"></script>
  <script src="{% static 'home/js/jquery.fancybox.min.js' %}"></script>
  <script src="{% static 'home/js/jquery.sticky.js' %}"></script>
  <script src="{% static 'home/js/jquery.mb.YTPlayer.min.js' %}"></script>
  <script src="{% static 'home/js/main.js' %}"></script>

</body>

</html>

{% endblock %}

home/templates/home/pages/basesub.html
{% extends 'home/pages/base.html' %}

{% load static %}

{% block content %}


    {% block coversection %}

        <div class="site-section ftco-subscribe-1 site-blocks-cover pb-4" style="background-image: url('{% static 'home/images/bg_1.jpg' %}')">
        <div class="container">
        {% block coveralignment %}
          <div class="row align-items-end">
        {% endblock %}
            <div class="col-lg-7">
                {% block coverslogan %}
                {% endblock %}
            </div>
          </div>
        </div>
      </div>


    <div class="custom-breadcrumns border-bottom">
      <div class="container">
        <a href="{% url 'home:home' %}">হোম</a>
        <span class="mx-3 icon-keyboard_arrow_right"></span>
         {% block covercurrent %}
         {% endblock %}
      </div>
    </div>

    {% endblock %}

    {% block mainsection %}

    {% endblock %}

{% endblock %}

teacher/templates/teacher/pages/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    In teacher html
</body>
</html>